# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

# Explicitly set the version of Python and its requirements
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
    
formats:  
  - pdf  
