[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "The Zombie Fridge Journal Manual"
authors = [{name = "The Zombie Fridge Journal"}]
dynamic = ["version", "description"]
